language: c++
before_script:
    - sudo apt-get install libsfml-dev
    - sudo apt-get install libboost1.54-all-dev
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_FLAGS="-std=c++11" ../
script: "make"
install: true
branches:
  only:
    - master
    - lb-refactor
