language: c++
compiler:
    - gcc
    - clang

before_install:
    - ls lib
    - ls lib/json-parser

install:
    - sudo apt-get install libsfml-dev
    - sudo apt-get install libboost-dev

before_script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_FLAGS="-std=c++11" ../
script: make

branches:
  only:
    - master
    - lb-refactor
