language: c++
compiler:
    - gcc
    - clang
before_script:
    - git submodule update --init --recursive
    - sudo apt-get install libsfml-dev
    - sudo apt-get install libboost-dev
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_FLAGS="-std=c++11" ../
script: make
install: true
branches:
  only:
    - master
    - lb-refactor
